name: Robot Framework Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install robotframework-pythonlibcore
          pip install selenium
          
      - name: Run app.py
        run: python app.py &

      - name: Run tests robot
        env:
          CHROME_LAUNCHER_ARGS: "--remote-debugging-port=9222 --headless"
        run: robot Robot_test.robot
